name: Coordinated Federated Learning
server:
  num-round: 50
  clients: 30
  model: LeNet
  data-name: CIFAR10
  parameters:
    load: True
    save: True
  validation: True
  data-mode: uneven
  client-selection: True
  client-cluster:
    enable: True
    cluster: AffinityPropagation
    KMeans:
      mode: auto
    AffinityPropagation:
      damping: 0.9
      max_iter: 1000


rabbit:
  address: 127.0.0.1
  username: admin
  password: admin

log_path: .

learning:
  learning-rate: 0.05
  momentum: 0.5
  batch-size: 128
