name: Coordinated Federated Learning
server:
  num-round: 30
  clients: 10
  model: LeNet_MNIST
  data-name: MNIST
  parameters:
    load: True
    save: True
  validation: True
  data-mode: uneven
  data-for-cluster: conference-each-client
  data-distribution:
    num-data-range:
      - 0
      - 500
    non-iid-rate: 0.5
    refresh-each-round: True
  conference-each-client:
    epoch-round-cluster: 4
    sample-foward-propagation: 1000
  random-seed: 1
  client-selection:
    enable: True
    mode: speed
  client-cluster:
    enable: True
    cluster: AffinityPropagation
    KMeans:
      mode: auto
    AffinityPropagation:
      damping: 0.9
      max_iter: 1000
  accuracy-drop: 20.0
  stop-when-false: False
  send-mail:
    active: False
    sender-email: 'example1@email.com'
    password: 'admin'
    receiver-email: 'example2@email.com'


rabbit:
  address: 197.0.0.00
  username: admin
  password: admin

log_path: .

learning:
  learning-rate: 0.0005
  momentum: 0.5
  batch-size: 128
  clip-grad-norm: 50
