name: Coordinated Federated Learning
server:
  num-round: 50
  clients: 2
  model: SimpleCNN
  data-name: MNIST
  parameters:
    load: False
    save: False
  validation: False
  data-mode: even
  client-selection: True
  client-cluster: True

rabbit:
  address: 127.0.0.1
  username: admin
  password: admin

log_path: .

learning:
  learning-rate: 1e-6
  momentum: 0.5
  batch-size: 256
