name: Coordinated Federated Learning
server:
  num-round: 2
  clients: 3
  model: LeNet_MNIST
  data-name: MNIST
  parameters:
    load: True
    save: True
  validation: False
  data-mode: uneven
  epoch_round_cluster: 2
  sample_cluster: 10
  data-distribution:
    num-data-range:
      - 0
      - 500
    non-iid-rate: 0.5
    refresh-each-round: True
  random-seed: 1
  client-selection:
    enable: True
    mode: speed
  client-cluster:
    enable: True
    cluster: AffinityPropagation
    KMeans:
      mode: auto
    AffinityPropagation:
      damping: 0.9
      max_iter: 1000
  accuracy-drop: 20.0
  stop-when-false: False
  send-mail:
    active: False
    sender-email: 'example1@email.com'
    password: 'admin'
    receiver-email: 'example2@email.com'


rabbit:
  address: 192.168.101.91
  username: dai 
  password: dai

log_path: .

learning:
  learning-rate: 0.05
  momentum: 0.5
  batch-size: 128
  clip-grad-norm: 0.0
